"""initial tables

Revision ID: f2cc7176b41c
Revises: 
Create Date: 2025-10-22 13:35:42.834204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2cc7176b41c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('varietal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('winery', sa.String(length=100), nullable=False),
    sa.Column('colour_id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('varietal_id', sa.Integer(), nullable=True),
    sa.Column('vintage_year', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('picture_path', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['colour_id'], ['colour.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['style_id'], ['style.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['varietal_id'], ['varietal.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('stock_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wine_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('transaction_type', sa.Enum('sale', 'purchase', name='transaction_type_enum'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['wine_id'], ['wine.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_movement')
    op.drop_table('wine')
    op.drop_table('varietal')
    op.drop_table('style')
    op.drop_table('shop')
    op.drop_table('colour')
    # ### end Alembic commands ###
